# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: .
  Archives: archives


social:
  email:
  twitter:
  weibo:
  github: sxcw
  googleplus:
  rss: 

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: #disqus _shortname
